Actualización UT
lunasoft/sw-sdk-java pull request #57
Opened 2022-01-06 18:38 UTC by martinfnsw

Actualización Cancelaciones
Actualización Consulta estatus
Actualización UT

2022-01-06 18:58 UTC, SwAeyrton commented on src/main/java/Utils/Requests/Cancelation/CancelationOptionsRequest.java
> +        super(token, URI + Constants.CANCELATION_UUID_PATH + rfc + "/" + uuid + "/" + "01" + "/" + "0e4c30b8-11d8-40d8-894d-ef8b32eb4bdf", proxyHost, proxyPort);
Aquí no debería ir las variables motivo y folioSustitucion?

2022-01-06 18:58 UTC, SwAeyrton commented on src/main/java/Utils/Requests/Cancelation/CancelationOptionsRequest.java
> +        this.motivo=motivo;
recomiendo seguir el mismo patron de las lineas anteriores

2022-01-06 18:58 UTC, SwAeyrton commented on src/main/java/Utils/Requests/Cancelation/CancelationOptionsRequest.java
> +    public String getmotivo() {
recomiendo utilizar camelCase

2022-01-06 19:05 UTC, rbarusta requested changes

2022-01-06 19:05 UTC, rbarusta commented on src/main/java/Utils/Requests/Cancelation/CancelationOptionsRequest.java
> +        super(token, URI + Constants.CANCELATION_UUID_PATH + rfc + "/" + uuid + "/" + "01" + "/" + "0e4c30b8-11d8-40d8-894d-ef8b32eb4bdf", proxyHost, proxyPort);
Esta quemado el 01 y el uuid no ?

2022-01-06 19:05 UTC, rbarusta commented on src/main/java/Utils/Requests/Cancelation/CancelationOptionsRequest.java
> +        super(token, URI + Constants.CANCELATION_UUID_PATH + rfc + "/" + uuid + "/" + "01" + "/" + "0e4c30b8-11d8-40d8-894d-ef8b32eb4bdf", proxyHost, proxyPort);
Puedes usar un string format para que sea un poco mas legible la concatenacion:
`String message = String.format("Hello! My name is %s, I'm %s.", name, age); `

2022-01-07 14:25 UTC, martinfnsw commented on src/main/java/Utils/Requests/Cancelation/CancelationOptionsRequest.java
> +        super(token, URI + Constants.CANCELATION_UUID_PATH + rfc + "/" + uuid + "/" + "01" + "/" + "0e4c30b8-11d8-40d8-894d-ef8b32eb4bdf", proxyHost, proxyPort);
Listo, corregido

2022-01-07 14:25 UTC, martinfnsw commented on src/main/java/Utils/Requests/Cancelation/CancelationOptionsRequest.java
> +        super(token, URI + Constants.CANCELATION_UUID_PATH + rfc + "/" + uuid + "/" + "01" + "/" + "0e4c30b8-11d8-40d8-894d-ef8b32eb4bdf", proxyHost, proxyPort);
Gracias, ya lo ajusté.

2022-01-07 14:29 UTC, martinfnsw commented on src/main/java/Utils/Requests/Cancelation/CancelationOptionsRequest.java
> +        super(token, URI + Constants.CANCELATION_UUID_PATH + rfc + "/" + uuid + "/" + "01" + "/" + "0e4c30b8-11d8-40d8-894d-ef8b32eb4bdf", proxyHost, proxyPort);
Correcto, ya quedó corregido.

2022-01-07 17:18 UTC, rbarusta approved these changes

2022-01-07 17:28 UTC, merged