Release/1.0.6.5
lunasoft/sw-sdk-java pull request #64
Opened 2022-05-09 18:50 UTC by SwAeyrton

2022-05-16 16:40 UTC, JuanGamezSW requested changes

2022-05-16 16:40 UTC, JuanGamezSW commented on src/main/java/Utils/Requests/Cancelation/CancelationRequest.java
> +					String uuid = xml.substring(xml.indexOf("<Folio UUID=") +13, xml.indexOf("Motivo")-2).toUpperCase();
Solo considerar que una cancelacion de XML puede contener multiples uuid.

2022-05-16 16:40 UTC, JuanGamezSW commented on src/main/java/Utils/Requests/StatusCfdi/StatusCancelationRequest.java
> +    private static SOAPMessage createSOAPRequest(String soapAction, String rfcEmisor, String rfcReceptor, String total, String uuid, String caract_sello) throws Exception {
x3

2022-05-17 21:41 UTC, SwAeyrton commented
@martinfnsw Juan te puso unos comentarios, ¿podrías apoyarnos a revisar?

2022-05-19 23:40 UTC, closed without merging