Feature/ss_199_CancelationService
lunasoft/sw-sdk-java pull request #77
Opened 2023-02-14 23:34 UTC by RonaldoNunezSW

## Describe los cambios
Se modifico método sendRequest y sendRequestPfx, puesto que tenia un error al tomar el dato foliofiscal null como string con valor "null" y no null directamente, ademas de mejorar el modo de setear el JSON con ayuda de JSONObject

## Ticket
SS-199: https://smarterweb.atlassian.net/browse/SS-199

## Ticket relacionados
MDA-56346  :https://smarterweb.atlassian.net/browse/MDA-56346

## Imagenes
N/A

2023-02-14 23:37 UTC, SwAeyrton requested changes
Falta actualizar la version y hay unas UT que estan fallando.

2023-02-14 23:37 UTC, SwAeyrton commented on src/main/java/Utils/Requests/Cancelation/CancelationRequest.java
> +                        obj.put("uuid",             ((CancelationOptionsRequest) request).getUuid());
Estos espacios son innecesarios

2023-02-15 00:03 UTC, RonaldoNunezSW commented on src/main/java/Utils/Requests/Cancelation/CancelationRequest.java
> +                        obj.put("uuid",             ((CancelationOptionsRequest) request).getUuid());
listo, los había colocado para mejorar la lectura de código

2023-02-15 15:54 UTC, SebastianSW approved these changes

2023-02-15 18:30 UTC, martinfnsw approved these changes

2023-02-16 16:50 UTC, SwAeyrton requested changes

2023-02-16 16:50 UTC, SwAeyrton commented on pom.xml
> +    <version>1.0.7.2</version>
esta version no es correcta, la rama develop ya va en la version 1.0.9.1, recuerda siempre actualizar la rama que vas a tomar para crear una rama feature, hotfix, o release.

2023-02-16 17:30 UTC, closed without merging