Hotfix/ss_199
lunasoft/sw-sdk-java pull request #78
Opened 2023-02-16 17:30 UTC by RonaldoNunezSW

## Describe los cambios
Se modifico método sendRequest y sendRequestPfx, puesto que tenia un error al tomar el dato foliofiscal null como string con valor "null" y no null directamente, ademas de mejorar el modo de setear el JSON con ayuda de JSONObject

## Ticket
SS-199: https://smarterweb.atlassian.net/browse/SS-199

## Ticket relacionados
MDA-56346  :https://smarterweb.atlassian.net/browse/MDA-56346

## Imagenes
N/A

2023-02-16 18:02 UTC, SebastianSW approved these changes

2023-02-16 18:23 UTC, FerCarrilloM approved these changes

2023-02-17 15:53 UTC, SwAeyrton commented
Siguen fallando algunas pruebas unitarias, 
![image](https://user-images.githubusercontent.com/88451104/219701826-3db9b743-1012-4b57-818d-eda428fafc47.png)

2023-02-17 15:53 UTC, SwAeyrton requested changes
Sugiero correr todas las UT en local antes de hacer el commit

2023-02-17 16:56 UTC, SebastianSW approved these changes

2023-02-17 17:26 UTC, SwAeyrton requested changes
Falta las UT probando el cambio.

2023-02-17 18:22 UTC, SwAeyrton approved these changes

2023-02-17 19:11 UTC, merged