Hotfix/SS-205
lunasoft/sw-sdk-java pull request #80
Opened 2023-05-12 20:16 UTC by SebastianSW

2023-05-15 16:57 UTC, SwAeyrton requested changes

2023-05-15 16:57 UTC, SwAeyrton commented on README.md
> +Alternativamente, tambin se cuenta con un archivo JAR en el que se incluyen todas las dependencias, este se encuentra en la carpeta [Relase Github](https://github.com/lunasoft/sw-sdk-java/releases),
Falta la e en tambin

2023-05-15 17:47 UTC, SebastianSW commented on README.md
> +Alternativamente, tambin se cuenta con un archivo JAR en el que se incluyen todas las dependencias, este se encuentra en la carpeta [Relase Github](https://github.com/lunasoft/sw-sdk-java/releases),
Se corrigió el error de escritura

2023-05-16 18:53 UTC, FerCarrilloM approved these changes

2023-05-16 22:22 UTC, ReyesSW approved these changes

2023-05-16 22:36 UTC, SwAeyrton approved these changes

2023-05-16 23:06 UTC, merged