Feature/update ut40
lunasoft/sw-sdk-java pull request #83
Opened 2023-09-21 02:26 UTC by marifersw

2023-09-21 15:50 UTC, SwAeyrton requested changes
Las UT de timbrado de CCE fallan, esto es porque el tipo de cambio USD cambia dia con dia, lo mejor es omitirlas.

2023-09-21 15:50 UTC, SwAeyrton commented on src/test/java/Tests/Cfdi40/CFDI40Test.java
> +            SuccessV2Response response = stampServiceToken.StampResponseV2("src/test/resources/CFDI40/CFDI40/CFDI40_Ingreso_KitParte.xml", "V2", true, false);
cuidar espacios en blanco

2023-09-21 19:29 UTC, ReyesSW approved these changes

2023-09-21 19:58 UTC, SebastianSW approved these changes

2023-09-21 20:15 UTC, FerCarrilloM approved these changes

2023-09-22 00:05 UTC, SwAeyrton approved these changes

2023-09-22 00:29 UTC, merged