Feature/ss 420
lunasoft/sw-sdk-java pull request #87
Opened 2023-10-19 14:47 UTC by ReyesSW

Se separan los request para Stamp Request Zip y Stam Request.
Se realizan las pruebas unitarias. Pasan exitosamente.
Se prueba el Stamp cuando el xml se pasa a base64.

2023-10-19 15:31 UTC, FerCarrilloM approved these changes

2023-10-19 15:47 UTC, SwAeyrton requested changes
falta actualizar la version

2023-10-19 16:56 UTC, ReyesSW commented on src/test/java/Tests/Cfdi40/Detallista131Test.java
> +    @Ignore
Se ignora porque requiere el XML sellado, y por su tamaño.

2023-10-19 17:20 UTC, ReyesSW commented
Se actualiza la version.

2023-10-19 17:21 UTC, SwAeyrton requested changes

2023-10-19 17:21 UTC, SwAeyrton commented on src/test/java/Tests/Cfdi40/CartaPorte20Test.java
> +    @Ignore
no se deben ignorar las UT

2023-10-19 18:22 UTC, martinfnsw approved these changes

2023-10-20 00:06 UTC, SwAeyrton approved these changes

2023-10-20 00:15 UTC, marifersw approved these changes

2023-10-20 00:27 UTC, merged