Feature/ss254yss444 account user
lunasoft/sw-sdk-java pull request #90
Opened 2023-12-11 09:27 UTC by marifersw

Realizacion de 2 task: SS-254 y SS-444: 
Se añade el metodo CSDByRFC al README
Se añade el servcio Users con sus diferentes clases y documentacion

2023-12-11 17:33 UTC, ReyesSW approved these changes

2023-12-11 17:34 UTC, ReyesSW approved these changes

2023-12-11 18:46 UTC, SebastianSW approved these changes

2023-12-11 19:18 UTC, FerCarrilloM approved these changes

2023-12-11 21:32 UTC, martinfnsw requested changes

2023-12-11 21:32 UTC, martinfnsw commented on src/main/java/Utils/Requests/Account/AccountUser/AccountUserRequest.java
> +    private JSONObject buildUserCreateJson(AccountUserOptionsRequest accountUserOptionsRequest) {
Algunas de estas funciones pueden estar en una clase helper

2023-12-11 21:32 UTC, martinfnsw commented on src/main/java/Utils/Responses/Account/AccountUser/AccountUserResponse.java
> +package Utils.Responses.Account.AccountUser;
Esta clase es casi idéntica a DataAccountUserResponse, ¿no es posible simplificar? O hay algún otro motivo por el que se dejaran así?

2023-12-11 22:10 UTC, marifersw commented on src/main/java/Utils/Responses/Account/AccountUser/AccountUserResponse.java
> +package Utils.Responses.Account.AccountUser;
Son 3 tipos de respuestas, solo cambia el tipo de dato de Data, en una es una lista para el metodo de todos los usuarios, otro es uno de tipo DataAccountUser para los metodos de get, y otro solo es un string por eso lo separe.

2023-12-12 07:51 UTC, SwAeyrton approved these changes

2023-12-13 18:11 UTC, martinfnsw approved these changes

2023-12-13 20:54 UTC, marifersw commented on src/main/java/Utils/Requests/Account/AccountUser/AccountUserOptionsRequest.java
> +public class AccountUserOptionsRequest extends IRequest {
Se agregaron mejores practicas de encapsulamiento

2023-12-13 20:57 UTC, merged