Feature/ss580
lunasoft/sw-sdk-java pull request #94
Opened 2024-05-21 00:44 UTC by FerCarrilloM

Se crea feature para modificar el método Stamp para que en base al peso del XML lo convierta y envié al servicio ZIP.

2024-05-21 15:44 UTC, SebastianSW approved these changes

2024-05-21 16:40 UTC, ReyesSW approved these changes

2024-05-21 17:10 UTC, SwAeyrton requested changes

2024-05-21 17:51 UTC, SwAeyrton commented on src/test/java/Tests/Cfdi40/CartaPorte20Test.java
> +    @Ignore
ah va, habría que derivarlo a un issue

2024-05-21 20:38 UTC, FerCarrilloM commented on src/main/java/Services/Stamp/SWStampService.java
> +		if (xmlFile.length > 35 * 1024 * 1024) {
Se crea un Helper para ayudar con el proceso y evitar duplicar código.

2024-05-21 20:38 UTC, FerCarrilloM commented on src/main/java/Services/Stamp/SWStampService.java
> +	private byte[] convertToZip(byte[] data) throws IOException {
Se crea un Helper para ayudar con el proceso y evitar duplicar código.

2024-05-21 22:13 UTC, marifersw approved these changes

2024-05-22 00:40 UTC, SwAeyrton approved these changes
![image](https://github.com/lunasoft/sw-sdk-java/assets/88451104/3101b7f6-5361-4a4b-a43e-1a53a24c244b)

2024-05-22 15:59 UTC, merged